// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package myfirstmodule.proxies;

public class SalesTrackingTable_2
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject salesTrackingTable_2MendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "MyFirstModule.SalesTrackingTable_2";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		OrderQuantity("OrderQuantity"),
		UnitPrice("UnitPrice"),
		DiscountAmount("DiscountAmount"),
		ProductStandardCost("ProductStandardCost"),
		TaxAmount("TaxAmount"),
		OrderDate("OrderDate"),
		ShipTime("ShipTime"),
		DueDate("DueDate"),
		SalesID("SalesID"),
		SalesTrackingTable_2_Customers("MyFirstModule.SalesTrackingTable_2_Customers"),
		SalesTrackingTable_2_Products("MyFirstModule.SalesTrackingTable_2_Products"),
		SalesTrackingTable_2_Locations("MyFirstModule.SalesTrackingTable_2_Locations"),
		SalesTrackingTable_2_SalesPerson("MyFirstModule.SalesTrackingTable_2_SalesPerson");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public SalesTrackingTable_2(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "MyFirstModule.SalesTrackingTable_2"));
	}

	protected SalesTrackingTable_2(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject salesTrackingTable_2MendixObject)
	{
		if (salesTrackingTable_2MendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("MyFirstModule.SalesTrackingTable_2", salesTrackingTable_2MendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a MyFirstModule.SalesTrackingTable_2");

		this.salesTrackingTable_2MendixObject = salesTrackingTable_2MendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'SalesTrackingTable_2.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static myfirstmodule.proxies.SalesTrackingTable_2 initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return myfirstmodule.proxies.SalesTrackingTable_2.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static myfirstmodule.proxies.SalesTrackingTable_2 initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new myfirstmodule.proxies.SalesTrackingTable_2(context, mendixObject);
	}

	public static myfirstmodule.proxies.SalesTrackingTable_2 load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return myfirstmodule.proxies.SalesTrackingTable_2.initialize(context, mendixObject);
	}

	public static java.util.List<myfirstmodule.proxies.SalesTrackingTable_2> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<myfirstmodule.proxies.SalesTrackingTable_2> result = new java.util.ArrayList<myfirstmodule.proxies.SalesTrackingTable_2>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//MyFirstModule.SalesTrackingTable_2" + xpathConstraint))
			result.add(myfirstmodule.proxies.SalesTrackingTable_2.initialize(context, obj));
		return result;
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of OrderQuantity
	 */
	public final java.lang.Integer getOrderQuantity()
	{
		return getOrderQuantity(getContext());
	}

	/**
	 * @param context
	 * @return value of OrderQuantity
	 */
	public final java.lang.Integer getOrderQuantity(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.OrderQuantity.toString());
	}

	/**
	 * Set value of OrderQuantity
	 * @param orderquantity
	 */
	public final void setOrderQuantity(java.lang.Integer orderquantity)
	{
		setOrderQuantity(getContext(), orderquantity);
	}

	/**
	 * Set value of OrderQuantity
	 * @param context
	 * @param orderquantity
	 */
	public final void setOrderQuantity(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer orderquantity)
	{
		getMendixObject().setValue(context, MemberNames.OrderQuantity.toString(), orderquantity);
	}

	/**
	 * @return value of UnitPrice
	 */
	public final java.math.BigDecimal getUnitPrice()
	{
		return getUnitPrice(getContext());
	}

	/**
	 * @param context
	 * @return value of UnitPrice
	 */
	public final java.math.BigDecimal getUnitPrice(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.UnitPrice.toString());
	}

	/**
	 * Set value of UnitPrice
	 * @param unitprice
	 */
	public final void setUnitPrice(java.math.BigDecimal unitprice)
	{
		setUnitPrice(getContext(), unitprice);
	}

	/**
	 * Set value of UnitPrice
	 * @param context
	 * @param unitprice
	 */
	public final void setUnitPrice(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal unitprice)
	{
		getMendixObject().setValue(context, MemberNames.UnitPrice.toString(), unitprice);
	}

	/**
	 * @return value of DiscountAmount
	 */
	public final java.math.BigDecimal getDiscountAmount()
	{
		return getDiscountAmount(getContext());
	}

	/**
	 * @param context
	 * @return value of DiscountAmount
	 */
	public final java.math.BigDecimal getDiscountAmount(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.DiscountAmount.toString());
	}

	/**
	 * Set value of DiscountAmount
	 * @param discountamount
	 */
	public final void setDiscountAmount(java.math.BigDecimal discountamount)
	{
		setDiscountAmount(getContext(), discountamount);
	}

	/**
	 * Set value of DiscountAmount
	 * @param context
	 * @param discountamount
	 */
	public final void setDiscountAmount(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal discountamount)
	{
		getMendixObject().setValue(context, MemberNames.DiscountAmount.toString(), discountamount);
	}

	/**
	 * @return value of ProductStandardCost
	 */
	public final java.math.BigDecimal getProductStandardCost()
	{
		return getProductStandardCost(getContext());
	}

	/**
	 * @param context
	 * @return value of ProductStandardCost
	 */
	public final java.math.BigDecimal getProductStandardCost(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.ProductStandardCost.toString());
	}

	/**
	 * Set value of ProductStandardCost
	 * @param productstandardcost
	 */
	public final void setProductStandardCost(java.math.BigDecimal productstandardcost)
	{
		setProductStandardCost(getContext(), productstandardcost);
	}

	/**
	 * Set value of ProductStandardCost
	 * @param context
	 * @param productstandardcost
	 */
	public final void setProductStandardCost(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal productstandardcost)
	{
		getMendixObject().setValue(context, MemberNames.ProductStandardCost.toString(), productstandardcost);
	}

	/**
	 * @return value of TaxAmount
	 */
	public final java.math.BigDecimal getTaxAmount()
	{
		return getTaxAmount(getContext());
	}

	/**
	 * @param context
	 * @return value of TaxAmount
	 */
	public final java.math.BigDecimal getTaxAmount(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.TaxAmount.toString());
	}

	/**
	 * Set value of TaxAmount
	 * @param taxamount
	 */
	public final void setTaxAmount(java.math.BigDecimal taxamount)
	{
		setTaxAmount(getContext(), taxamount);
	}

	/**
	 * Set value of TaxAmount
	 * @param context
	 * @param taxamount
	 */
	public final void setTaxAmount(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal taxamount)
	{
		getMendixObject().setValue(context, MemberNames.TaxAmount.toString(), taxamount);
	}

	/**
	 * @return value of OrderDate
	 */
	public final java.util.Date getOrderDate()
	{
		return getOrderDate(getContext());
	}

	/**
	 * @param context
	 * @return value of OrderDate
	 */
	public final java.util.Date getOrderDate(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.OrderDate.toString());
	}

	/**
	 * Set value of OrderDate
	 * @param orderdate
	 */
	public final void setOrderDate(java.util.Date orderdate)
	{
		setOrderDate(getContext(), orderdate);
	}

	/**
	 * Set value of OrderDate
	 * @param context
	 * @param orderdate
	 */
	public final void setOrderDate(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date orderdate)
	{
		getMendixObject().setValue(context, MemberNames.OrderDate.toString(), orderdate);
	}

	/**
	 * @return value of ShipTime
	 */
	public final java.util.Date getShipTime()
	{
		return getShipTime(getContext());
	}

	/**
	 * @param context
	 * @return value of ShipTime
	 */
	public final java.util.Date getShipTime(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.ShipTime.toString());
	}

	/**
	 * Set value of ShipTime
	 * @param shiptime
	 */
	public final void setShipTime(java.util.Date shiptime)
	{
		setShipTime(getContext(), shiptime);
	}

	/**
	 * Set value of ShipTime
	 * @param context
	 * @param shiptime
	 */
	public final void setShipTime(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date shiptime)
	{
		getMendixObject().setValue(context, MemberNames.ShipTime.toString(), shiptime);
	}

	/**
	 * @return value of DueDate
	 */
	public final java.util.Date getDueDate()
	{
		return getDueDate(getContext());
	}

	/**
	 * @param context
	 * @return value of DueDate
	 */
	public final java.util.Date getDueDate(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.DueDate.toString());
	}

	/**
	 * Set value of DueDate
	 * @param duedate
	 */
	public final void setDueDate(java.util.Date duedate)
	{
		setDueDate(getContext(), duedate);
	}

	/**
	 * Set value of DueDate
	 * @param context
	 * @param duedate
	 */
	public final void setDueDate(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date duedate)
	{
		getMendixObject().setValue(context, MemberNames.DueDate.toString(), duedate);
	}

	/**
	 * @return value of SalesID
	 */
	public final java.lang.Long getSalesID()
	{
		return getSalesID(getContext());
	}

	/**
	 * @param context
	 * @return value of SalesID
	 */
	public final java.lang.Long getSalesID(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Long) getMendixObject().getValue(context, MemberNames.SalesID.toString());
	}

	/**
	 * Set value of SalesID
	 * @param salesid
	 */
	public final void setSalesID(java.lang.Long salesid)
	{
		setSalesID(getContext(), salesid);
	}

	/**
	 * Set value of SalesID
	 * @param context
	 * @param salesid
	 */
	public final void setSalesID(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Long salesid)
	{
		getMendixObject().setValue(context, MemberNames.SalesID.toString(), salesid);
	}

	/**
	 * @return value of SalesTrackingTable_2_Customers
	 */
	public final myfirstmodule.proxies.Customers getSalesTrackingTable_2_Customers() throws com.mendix.core.CoreException
	{
		return getSalesTrackingTable_2_Customers(getContext());
	}

	/**
	 * @param context
	 * @return value of SalesTrackingTable_2_Customers
	 */
	public final myfirstmodule.proxies.Customers getSalesTrackingTable_2_Customers(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		myfirstmodule.proxies.Customers result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.SalesTrackingTable_2_Customers.toString());
		if (identifier != null)
			result = myfirstmodule.proxies.Customers.load(context, identifier);
		return result;
	}

	/**
	 * Set value of SalesTrackingTable_2_Customers
	 * @param salestrackingtable_2_customers
	 */
	public final void setSalesTrackingTable_2_Customers(myfirstmodule.proxies.Customers salestrackingtable_2_customers)
	{
		setSalesTrackingTable_2_Customers(getContext(), salestrackingtable_2_customers);
	}

	/**
	 * Set value of SalesTrackingTable_2_Customers
	 * @param context
	 * @param salestrackingtable_2_customers
	 */
	public final void setSalesTrackingTable_2_Customers(com.mendix.systemwideinterfaces.core.IContext context, myfirstmodule.proxies.Customers salestrackingtable_2_customers)
	{
		if (salestrackingtable_2_customers == null)
			getMendixObject().setValue(context, MemberNames.SalesTrackingTable_2_Customers.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.SalesTrackingTable_2_Customers.toString(), salestrackingtable_2_customers.getMendixObject().getId());
	}

	/**
	 * @return value of SalesTrackingTable_2_Products
	 */
	public final myfirstmodule.proxies.Products getSalesTrackingTable_2_Products() throws com.mendix.core.CoreException
	{
		return getSalesTrackingTable_2_Products(getContext());
	}

	/**
	 * @param context
	 * @return value of SalesTrackingTable_2_Products
	 */
	public final myfirstmodule.proxies.Products getSalesTrackingTable_2_Products(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		myfirstmodule.proxies.Products result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.SalesTrackingTable_2_Products.toString());
		if (identifier != null)
			result = myfirstmodule.proxies.Products.load(context, identifier);
		return result;
	}

	/**
	 * Set value of SalesTrackingTable_2_Products
	 * @param salestrackingtable_2_products
	 */
	public final void setSalesTrackingTable_2_Products(myfirstmodule.proxies.Products salestrackingtable_2_products)
	{
		setSalesTrackingTable_2_Products(getContext(), salestrackingtable_2_products);
	}

	/**
	 * Set value of SalesTrackingTable_2_Products
	 * @param context
	 * @param salestrackingtable_2_products
	 */
	public final void setSalesTrackingTable_2_Products(com.mendix.systemwideinterfaces.core.IContext context, myfirstmodule.proxies.Products salestrackingtable_2_products)
	{
		if (salestrackingtable_2_products == null)
			getMendixObject().setValue(context, MemberNames.SalesTrackingTable_2_Products.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.SalesTrackingTable_2_Products.toString(), salestrackingtable_2_products.getMendixObject().getId());
	}

	/**
	 * @return value of SalesTrackingTable_2_Locations
	 */
	public final myfirstmodule.proxies.Locations getSalesTrackingTable_2_Locations() throws com.mendix.core.CoreException
	{
		return getSalesTrackingTable_2_Locations(getContext());
	}

	/**
	 * @param context
	 * @return value of SalesTrackingTable_2_Locations
	 */
	public final myfirstmodule.proxies.Locations getSalesTrackingTable_2_Locations(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		myfirstmodule.proxies.Locations result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.SalesTrackingTable_2_Locations.toString());
		if (identifier != null)
			result = myfirstmodule.proxies.Locations.load(context, identifier);
		return result;
	}

	/**
	 * Set value of SalesTrackingTable_2_Locations
	 * @param salestrackingtable_2_locations
	 */
	public final void setSalesTrackingTable_2_Locations(myfirstmodule.proxies.Locations salestrackingtable_2_locations)
	{
		setSalesTrackingTable_2_Locations(getContext(), salestrackingtable_2_locations);
	}

	/**
	 * Set value of SalesTrackingTable_2_Locations
	 * @param context
	 * @param salestrackingtable_2_locations
	 */
	public final void setSalesTrackingTable_2_Locations(com.mendix.systemwideinterfaces.core.IContext context, myfirstmodule.proxies.Locations salestrackingtable_2_locations)
	{
		if (salestrackingtable_2_locations == null)
			getMendixObject().setValue(context, MemberNames.SalesTrackingTable_2_Locations.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.SalesTrackingTable_2_Locations.toString(), salestrackingtable_2_locations.getMendixObject().getId());
	}

	/**
	 * @return value of SalesTrackingTable_2_SalesPerson
	 */
	public final myfirstmodule.proxies.SalesPerson getSalesTrackingTable_2_SalesPerson() throws com.mendix.core.CoreException
	{
		return getSalesTrackingTable_2_SalesPerson(getContext());
	}

	/**
	 * @param context
	 * @return value of SalesTrackingTable_2_SalesPerson
	 */
	public final myfirstmodule.proxies.SalesPerson getSalesTrackingTable_2_SalesPerson(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		myfirstmodule.proxies.SalesPerson result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.SalesTrackingTable_2_SalesPerson.toString());
		if (identifier != null)
			result = myfirstmodule.proxies.SalesPerson.load(context, identifier);
		return result;
	}

	/**
	 * Set value of SalesTrackingTable_2_SalesPerson
	 * @param salestrackingtable_2_salesperson
	 */
	public final void setSalesTrackingTable_2_SalesPerson(myfirstmodule.proxies.SalesPerson salestrackingtable_2_salesperson)
	{
		setSalesTrackingTable_2_SalesPerson(getContext(), salestrackingtable_2_salesperson);
	}

	/**
	 * Set value of SalesTrackingTable_2_SalesPerson
	 * @param context
	 * @param salestrackingtable_2_salesperson
	 */
	public final void setSalesTrackingTable_2_SalesPerson(com.mendix.systemwideinterfaces.core.IContext context, myfirstmodule.proxies.SalesPerson salestrackingtable_2_salesperson)
	{
		if (salestrackingtable_2_salesperson == null)
			getMendixObject().setValue(context, MemberNames.SalesTrackingTable_2_SalesPerson.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.SalesTrackingTable_2_SalesPerson.toString(), salestrackingtable_2_salesperson.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return salesTrackingTable_2MendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final myfirstmodule.proxies.SalesTrackingTable_2 that = (myfirstmodule.proxies.SalesTrackingTable_2) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "MyFirstModule.SalesTrackingTable_2";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
